<?php

namespace OVE\ProceduresBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * groupesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class groupesRepository extends EntityRepository
{
}
