<?php

namespace OVE\ProceduresBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * parametresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class parametresRepository extends EntityRepository
{
}
