<?php

namespace OVE\ProceduresBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * tramesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tramesRepository extends EntityRepository
{
}
